name: alghwalbi_dropdown
description: "A custom dropdown package for Flutter projects, designed for personal use."
version: 0.0.1
homepage: https://github.com/ahmedabdelrahmanalghwalbi/alghwalbi_dropdown

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: